apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: test
spec:
    spec:
      containers:
        - name: test
          oooh: hmmm
          image: nahsilabs/test:0.0.4 # x-release-please-version
